name: Build Yoga

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install llvm-mingw
        env:
          LLVM_MINGW_VERSION: "20260922"
        run: |
          mkdir -p "$RUNNER_TEMP/llvm-mingw"
          curl -fsSL "https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_VERSION/llvm-mingw-$LLVM_MINGW_VERSION-ucrt-ubuntu-22.04-x86_64.tar.xz" \
            | tar xJ -C "$RUNNER_TEMP/llvm-mingw" --strip-components=1
          echo "$RUNNER_TEMP/llvm-mingw/bin" >> "$GITHUB_PATH"

      - name: Build x64
        run: bash -e build_unix.sh x64

      - name: Build ARM64
        run: bash -e build_unix.sh arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: yoga-${{ github.sha }}
          path: 'build/'
          if-no-files-found: 'error'

  pack:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifests
        uses: actions/checkout@v5
        with:
          sparse-checkout: manifests

      - name: Download Yoga binary
        uses: actions/download-artifact@v5
        with:
          name: yoga-${{ github.sha }}
          path: './artifacts'

      - name: Prepare package folder
        run: |
          mkdir -p package/Libs/Native/arm64
          mkdir -p package/Plugins
          cp artifacts/yoga.dll package/Libs/Native/yoga.dll
          cp artifacts/arm64/yoga.dll package/Libs/Native/arm64/yoga.dll

      - name: Generate BSIPA manifest
        run: |
          GAME_VERSION="1.42.0" \
          YOGA_VERSION=$(cat artifacts/VERSION) \
          envsubst < manifests/BeatSaber.json.in > package/Plugins/Yoga.manifest

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v5
        with:
          name: yoga-bs-${{ github.sha }}
          path: './package'
          if-no-files-found: 'error'
